var _driver_8h =
[
    [ "FILE_RECORD_HEADER", "struct_f_i_l_e___r_e_c_o_r_d___h_e_a_d_e_r.html", "struct_f_i_l_e___r_e_c_o_r_d___h_e_a_d_e_r" ],
    [ "ATTR_HEADER_RES", "struct_a_t_t_r___h_e_a_d_e_r___r_e_s.html", "struct_a_t_t_r___h_e_a_d_e_r___r_e_s" ],
    [ "ATTR_HEADER_NONRES", "struct_a_t_t_r___h_e_a_d_e_r___n_o_n_r_e_s.html", "struct_a_t_t_r___h_e_a_d_e_r___n_o_n_r_e_s" ],
    [ "ATTR_LIST_RECORD", "struct_a_t_t_r___l_i_s_t___r_e_c_o_r_d.html", "struct_a_t_t_r___l_i_s_t___r_e_c_o_r_d" ],
    [ "INDEX_ENTRY", "struct_i_n_d_e_x___e_n_t_r_y.html", "struct_i_n_d_e_x___e_n_t_r_y" ],
    [ "INDEX_HEADER", "struct_i_n_d_e_x___h_e_a_d_e_r.html", "struct_i_n_d_e_x___h_e_a_d_e_r" ],
    [ "INDEX_RECORD_HEADER", "struct_i_n_d_e_x___r_e_c_o_r_d___h_e_a_d_e_r.html", "struct_i_n_d_e_x___r_e_c_o_r_d___h_e_a_d_e_r" ],
    [ "INDEX_ROOT", "struct_i_n_d_e_x___r_o_o_t.html", "struct_i_n_d_e_x___r_o_o_t" ],
    [ "ATTR_INDEX_ROOT", "struct_a_t_t_r___i_n_d_e_x___r_o_o_t.html", "struct_a_t_t_r___i_n_d_e_x___r_o_o_t" ],
    [ "ATTR_FILE_NAME", "struct_a_t_t_r___f_i_l_e___n_a_m_e.html", "struct_a_t_t_r___f_i_l_e___n_a_m_e" ],
    [ "BOOT_FILE_DATA", "struct_b_o_o_t___f_i_l_e___d_a_t_a.html", "struct_b_o_o_t___f_i_l_e___d_a_t_a" ],
    [ "SYMLINK", "struct_s_y_m_l_i_n_k.html", "struct_s_y_m_l_i_n_k" ],
    [ "NTFS_ATTR", "struct_n_t_f_s___a_t_t_r.html", "struct_n_t_f_s___a_t_t_r" ],
    [ "_NTFS_FILE", "struct___n_t_f_s___f_i_l_e.html", "struct___n_t_f_s___f_i_l_e" ],
    [ "_EFI_NTFS_FILE", "struct___e_f_i___n_t_f_s___f_i_l_e.html", "struct___e_f_i___n_t_f_s___f_i_l_e" ],
    [ "_EFI_FS", "struct___e_f_i___f_s.html", "struct___e_f_i___f_s" ],
    [ "UNIT_ELEMENT", "struct_u_n_i_t___e_l_e_m_e_n_t.html", "struct_u_n_i_t___e_l_e_m_e_n_t" ],
    [ "COMPRESSED", "struct_c_o_m_p_r_e_s_s_e_d.html", "struct_c_o_m_p_r_e_s_s_e_d" ],
    [ "RUNLIST", "struct_r_u_n_l_i_s_t.html", "struct_r_u_n_l_i_s_t" ],
    [ "ATTRIBUTES_END_MARKER", "_driver_8h.html#a17972b1ecb4eaca9486a30a383236110", null ],
    [ "COMPRESSION_BLOCK", "_driver_8h.html#ae6f71bfb7afd3cbff527c9f98c2be62b", null ],
    [ "MAX_FILE_SIZE", "_driver_8h.html#a649ad5274d988d17a275a3cead056746", null ],
    [ "MAX_PATH", "_driver_8h.html#ab99ded389af74001a6298fc9e44e74e5", null ],
    [ "MINIMUM_FS_INFO_LENGTH", "_driver_8h.html#a1fc19a6371725e098bc1dd2dad00236a", null ],
    [ "MINIMUM_INFO_LENGTH", "_driver_8h.html#ac570e2fe41f5efae96ad2fbc579d435e", null ],
    [ "NTFS_DRIVER_VERSION", "_driver_8h.html#adf7dcaa1959073c7582edd3f2d27dcc6", null ],
    [ "NTFS_MAX_IDX", "_driver_8h.html#a87d23a618c0a378831fd5a4105fc61f0", null ],
    [ "NTFS_MAX_MFT", "_driver_8h.html#a7ee65eb4c150ed3ffcf89c4942490d82", null ],
    [ "S_FILENAME", "_driver_8h.html#ae47bc3f189ce985948279f59df05d5fe", null ],
    [ "S_SYMLINK", "_driver_8h.html#a07101543016c50b710c614ce6f8059b2", null ],
    [ "EFI_FS", "_driver_8h.html#a9f8f92c4c728c21eed1de5738c194cbf", null ],
    [ "EFI_NTFS_FILE", "_driver_8h.html#ab77dff5c0cfce782546d0f426a27bc0a", null ],
    [ "NTFS_FILE", "_driver_8h.html#a9e21ea9e3b85e547c573aa69bb07c311", null ]
];