var searchData=
[
  ['validateacpi_2ec_0',['ValidateAcpi.c',['../_validate_acpi_8c.html',1,'']]],
  ['validatebooter_2ec_1',['ValidateBooter.c',['../_validate_booter_8c.html',1,'']]],
  ['validatedeviceproperties_2ec_2',['ValidateDeviceProperties.c',['../_validate_device_properties_8c.html',1,'']]],
  ['validatekernel_2ec_3',['ValidateKernel.c',['../_validate_kernel_8c.html',1,'']]],
  ['validatemisc_2ec_4',['ValidateMisc.c',['../_validate_misc_8c.html',1,'']]],
  ['validatenvram_2ec_5',['ValidateNvram.c',['../_validate_nvram_8c.html',1,'']]],
  ['validateplatforminfo_2ec_6',['ValidatePlatformInfo.c',['../_validate_platform_info_8c.html',1,'']]],
  ['validateuefi_2ec_7',['ValidateUefi.c',['../_validate_uefi_8c.html',1,'']]],
  ['variablemanagement_2ec_8',['VariableManagement.c',['../_variable_management_8c.html',1,'']]],
  ['verifymemopt_2ec_9',['VerifyMemOpt.c',['../_verify_mem_opt_8c.html',1,'']]],
  ['verifymsre2_2ec_10',['VerifyMsrE2.c',['../_verify_msr_e2_8c.html',1,'']]],
  ['versioncompare_2ec_11',['VersionCompare.c',['../_version_compare_8c.html',1,'']]],
  ['vgaminiport_2eh_12',['VgaMiniPort.h',['../_vga_mini_port_8h.html',1,'']]],
  ['virtualdir_2ec_13',['VirtualDir.c',['../_virtual_dir_8c.html',1,'']]],
  ['virtualfile_2ec_14',['VirtualFile.c',['../_virtual_file_8c.html',1,'']]],
  ['virtualfs_2ec_15',['VirtualFs.c',['../_virtual_fs_8c.html',1,'']]],
  ['virtualfsinternal_2eh_16',['VirtualFsInternal.h',['../_virtual_fs_internal_8h.html',1,'']]],
  ['virtualmemory_2ec_17',['VirtualMemory.c',['../_virtual_memory_8c.html',1,'']]],
  ['virtualmemory_2eh_18',['VirtualMemory.h',['../_utilities_2_base_tools_2_virtual_memory_8h.html',1,'(Global Namespace)'],['../_include_2_intel_2_industry_standard_2_virtual_memory_8h.html',1,'(Global Namespace)']]],
  ['virtualvolume_2ec_19',['VirtualVolume.c',['../_virtual_volume_8c.html',1,'']]],
  ['vmwaredebug_2eh_20',['VMwareDebug.h',['../_v_mware_debug_8h.html',1,'']]],
  ['vmwarehda_2eh_21',['VMwareHda.h',['../_v_mware_hda_8h.html',1,'']]],
  ['vmwaremac_2eh_22',['VMwareMac.h',['../_v_mware_mac_8h.html',1,'']]],
  ['vtables_2ec_23',['Vtables.c',['../_vtables_8c.html',1,'']]]
];
