name: OcSrcDocs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-oc-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        id: get_tag
        run: |
          latesttag=$(curl -s https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest | jq -r .tag_name)
          currenttag=$(<oc-tag.txt)
          echo is_modified=$([[ $latesttag == $currenttag ]] && echo "no" || echo "yes") >> $GITHUB_OUTPUT
          echo tag=$currenttag >> $GITHUB_OUTPUT

      - name: Checkout Oc
        if: steps.get_tag.outputs.is_modified == 'yes'
        uses: actions/checkout@v3
        with:
          repository: acidanthera/OpenCorePkg
          path: OpenCorePkg
          ref: ${{ steps.get_tag.outputs.tag }}
          fetch-depth: 1

      - name: Install Files
        if: steps.get_tag.outputs.is_modified == 'yes'
        run: |
          cp ./Doxyfile OpenCorePkg/
          cp ./assets/* OpenCorePkg/
          cp OpenCorePkg/Docs/Logos/LogoApprox.svg OpenCorePkg/
          mkdir -p OpenCorePkg/Doxy/html/ && cp ./assets/favicon.ico OpenCorePkg/Doxy/html/
          sed -i 's/@OC_VERSION@/${{ steps.get_tag.outputs.tag }}/g' OpenCorePkg/Doxyfile
          sed -i 's/@OC_VERSION@/${{ steps.get_tag.outputs.tag }}/g' OpenCorePkg/mainpage.md

      - name: Doxygen Action
        if: steps.get_tag.outputs.is_modified == 'yes'
        uses: mattnotmitt/doxygen-action@v1
        with:
            doxyfile-path: ./Doxyfile
            working-directory: OpenCorePkg/

      - name: GH Pages Deployment
        if: steps.get_tag.outputs.is_modified == 'yes'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./OpenCorePkg/Doxy/html/
          enable_jekyll: false
          allow_empty_commit: true
          force_orphan: true
          publish_branch: gh-pages
