name: OcSrcDocs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-oc-docs:
    runs-on: ubuntu-latest

    env:
      versioncheckpath: 'oc-tag.txt'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get Tag
        id: get_tag
        run: |
          curl -s https://api.github.com/repos/acidanthera/OpenCorePkg/releases/latest | jq -r .tag_name > ${{ env.versioncheckpath }}
          echo tag=$(<${{ env.versioncheckpath }}) >> $GITHUB_OUTPUT

      - name: Compare
        id: compare
        run: echo is_modified=$([ -z "`git status --porcelain`" ] && echo "no" || echo "yes") >> $GITHUB_OUTPUT

      - name: Import GPG key
        if: steps.compare.outputs.is_modified == 'yes'
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Commit the updates
        if: steps.compare.outputs.is_modified == 'yes'
        uses: EndBug/add-and-commit@v9
        with:
          add: '${{ env.versioncheckpath }}'
          message: automated update
          push: true

      - name: Checkout Oc
        if: steps.compare.outputs.is_modified == 'yes'
        uses: actions/checkout@v3
        with:
          repository: acidanthera/OpenCorePkg
          path: OpenCorePkg
          ref: ${{ steps.get_tag.outputs.tag }}
          fetch-depth: 1

      - name: Install Files
        if: steps.compare.outputs.is_modified == 'yes'
        run: |
          cp ./Doxyfile OpenCorePkg/
          cp ./assets/* OpenCorePkg/
          cp OpenCorePkg/Docs/Logos/LogoApprox.svg OpenCorePkg/
          mkdir -p OpenCorePkg/Doxy/html/ && cp ./assets/favicon.ico OpenCorePkg/Doxy/html/
          sed -i 's/@OC_VERSION@/${{ steps.get_tag.outputs.tag }}/g' OpenCorePkg/Doxyfile
          sed -i 's/@OC_VERSION@/${{ steps.get_tag.outputs.tag }}/g' OpenCorePkg/mainpage.md

      - name: Doxygen Action
        if: steps.compare.outputs.is_modified == 'yes'
        uses: mattnotmitt/doxygen-action@v1
        with:
            doxyfile-path: ./Doxyfile
            working-directory: OpenCorePkg/

      - name: GH Pages Deployment
        if: steps.compare.outputs.is_modified == 'yes'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./OpenCorePkg/Doxy/html/
          enable_jekyll: false
          allow_empty_commit: true
          force_orphan: true
          publish_branch: gh-pages
